# Site settings
title: Sam Spaulding
email: samuelsp@media.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Samuel Spaulding
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.samspaulding.com" # the base hostname & protocol for your site
twitter_username: SpauldingSam
github_username:  samspaulding

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "PhD Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""